### ISSUE TITLE
Use of `find_package` rather than `find_dependency`

### ISSUE THREAD

**Issue by rleigh-codelibre** [boost-cmake/boost#1]
Logic such as this:

```
if(boost_throw_exception_FOUND)
file(APPEND "${PROJECT_BINARY_DIR}/boost_mpi-config.cmake" "
find_package(boost_throw_exception)
")
```

should be using `find_dependency` (from `CMakeFindDependencyMacro`).  This is equivalent to `find_package` but is specifically for use in recursive calls inside configuration scripts.

**Comment by pfultz2** [comment]
Yes, totally agree, this was a complete oversight.
