### ISSUE TITLE
Handling of missing build dependencies

### ISSUE THREAD

**Issue by rleigh-codelibre** [boost-cmake/boost#2]
```
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)                         
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH)
```

Currently it seems that missing build dependencies results in a build failure, rather than skipping of optional components.  Has this been discussed previously?  Strategies could include:

- having a cache variable set to ON|OFF|AUTO and have it fail if not present and set to ON, build if present and set to AUTO, or not build if set to OFF
- always autodetecting and building/not building if available/not available

**Comment by pfultz2** [comment]
Ideally, I am thinking of doing `find_package(MPI)` in the top-level cmake, and then if its missing just skip those the MPI libraries.

**Comment by rleigh-codelibre** [comment]
That would make complete sense.  The top-level has the overview of the whole build, and it would fit there.

**Comment by pfultz2** [comment]
So this has been updated to make this optional.
